### ISSUE TITLE
fetchparams matches too greedily

### ISSUE THREAD

**Issue by Acefall** [Eredost/attributes-router#18]
Consider the following route
`#[Route('event/{eventId<\d+>}/user/{userId<\d+>}/vote', name: 'someName', methods: ['POST'])]`

The fetchParams function returns `["eventId" => ""\d+>}/user/{userId<\d+"]`. It matches too greedily.

Modifying the regex from `/{([\w\-%]+)(?:<(.+)>)?}/` to `/{([\w\-%]+)(?:<(.+?)>)?}/` solves the issue.

**Comment by Eredost** [comment]
Associated PR merged.
